Repository BCSDLab/JJBAKSA_FRONT_END, pull requests merged in 2022-09, with the labels that each got.

#7 Feature/#1 media query utils 추가
  src/utils/hooks/useMediaQuery.ts
  src/utils/styles/mediaQuery.scss
Labels: New Feature

#9 Feature/#1 모바일 하단 네비게이션 추가
  .stylelint.json
  src/App.tsx
  src/assets/svg/home.svg
  src/assets/svg/my-page.svg
  src/assets/svg/write.svg
  src/components/common/BottomNavigation/BottomNavigation.module.scss
  src/components/common/BottomNavigation/index.tsx
  src/layout/DefaultLayout/index.tsx
  src/utils/hooks/useMediaQuery.ts
  src/utils/ts/classNames.ts
Labels: New Feature

#14 #13 폰트 로딩 불가
  src/styles/fonts.scss
Labels: bug

#15 #12 user apiClient, 타입 interface 정의
  .gitignore
  package.json
  src/api/index.ts
  src/api/user/entity.ts
  src/api/user/index.ts
  src/api/user/userApiClient.ts
  src/index.tsx
  yarn.lock
Labels: New Feature

#17 Feature/#8 웹폰트 로드 중 텍스트 표시 속성 추가
  src/utils/styles/mixin/index.scss
Labels: enhancement
