Repository BCSDLab/JJBAKSA_FRONT_END, pull requests merged in 2023-11, with the labels that each got.

#112 [SEARCH] 검색 결과 페이지 구현
  src/api/search/entity.ts
  src/api/search/index.ts
  src/api/shop/entity.ts
  src/api/shop/index.ts
  src/assets/images/search/defaultImage.png
  src/assets/svg/search/phone.svg
  src/components/common/SideNavigation/index.tsx
  src/pages/Home/components/Map/hooks/useFilterShops.ts
  src/pages/Home/components/Map/index.tsx
  src/pages/Search/components/RelatedSearches/RelatedSearches.module.scss
  src/pages/Search/components/SearchBar/SearchBar.module.scss
  src/pages/Search/components/SearchBar/SearchInput.tsx
  src/pages/Search/hooks/useSearchingMode.ts
  src/pages/Search/index.tsx
  src/pages/SearchDetails/SearchDetails.module.scss
  src/pages/SearchDetails/components/LoadingView.tsx
  src/pages/SearchDetails/components/SearchItem.tsx
  src/pages/SearchDetails/hooks/useFetchAutoComplete.ts
  src/pages/SearchDetails/hooks/useFetchShops.ts
  src/pages/SearchDetails/index.tsx
  src/pages/SearchDetails/static/mockup.ts
  src/store/location.ts
  src/utils/hooks/useDebounce.ts
  src/utils/hooks/useGeolocation.ts
Labels: enhancement, UI

#115 [HOTFIX] Mock 데이터 삭제로 인한 에러 해결
  src/pages/SearchDetails/static/mockup.ts
Labels: bug

#117 [공통] 검색 API 모킹
  .github/workflows/LINT_CHECK.yml
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/api/shop/entity.ts
  src/components/Pagination/index.tsx
  src/components/PreviousButton/PreviousButton.tsx
  src/components/StarRating/EnterStarRateContainer.tsx
  src/components/StarRating/LeaveStarRateContainer.tsx
  src/components/editor/TextEditor/AddImage/index.tsx
  src/components/editor/TextEditor/AddImageFile/index.tsx
  src/index.tsx
  src/mocks/api/data/shopsResultData.ts
  src/mocks/api/shopsResult.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/Auth/Login/index.tsx
  src/pages/Search/components/RelatedSearches/components/ToggleButton.tsx
  src/pages/Search/components/SearchBar/SearchInput.tsx
  src/pages/Search/index.tsx
  src/pages/SearchDetails/index.tsx
  src/pages/Setting/Mobile/index.tsx
  src/pages/Setting/PC/Service.tsx
  src/pages/ShopDetail/components/ImageCarousel/index.tsx
  src/store/text.ts
  yarn.lock
Labels: enhancement
