Repository BCSDLab/JJBAKSA_FRONT_END, pull requests merged in 2024-01, with the labels that each got.

#129 [INQUIRY] 문의하기 페이지 기능
  src/App.tsx
  src/api/inquiry/entity.ts
  src/api/inquiry/index.ts
  src/api/inquiry/inquire/index.ts
  src/api/inquiry/inquiry/index.ts
  src/api/inquiry/inquiryApiClient.ts
  src/assets/svg/inquiry/image-delete.svg
  src/pages/Inquiry/Inquire/components/InquireForm/InquireForm.module.scss
  src/pages/Inquiry/Inquire/components/InquireForm/RequiredLabel/RequiredLabel.module.scss
  src/pages/Inquiry/Inquire/components/InquireForm/RequiredLabel/index.tsx
  src/pages/Inquiry/Inquire/components/InquireForm/index.tsx
  src/pages/Inquiry/Inquiry/Inquiry.module.scss
  src/pages/Inquiry/Inquiry/components/InquiryList/InquiryBlock/Answer/Answer.module.scss
  src/pages/Inquiry/Inquiry/components/InquiryList/InquiryBlock/Answer/index.tsx
  src/pages/Inquiry/Inquiry/components/InquiryList/InquiryBlock/InquiryBlock.module.scss
  src/pages/Inquiry/Inquiry/components/InquiryList/InquiryBlock/InquiryImages/InquiryImages.module.scss
  src/pages/Inquiry/Inquiry/components/InquiryList/InquiryBlock/InquiryImages/index.tsx
  src/pages/Inquiry/Inquiry/components/InquiryList/InquiryBlock/index.tsx
  src/pages/Inquiry/Inquiry/components/InquiryList/InquiryList.module.scss
  src/pages/Inquiry/Inquiry/components/InquiryList/index.tsx
  src/pages/Inquiry/Inquiry/components/InquirySelectButton/index.tsx
  src/pages/Inquiry/Inquiry/hooks/useInquiryList.ts
  src/pages/Inquiry/Inquiry/index.tsx
  src/pages/Inquiry/hooks/useGetInquiry.ts
  src/pages/Inquiry/hooks/useInquiryImages.ts
  src/pages/Inquiry/hooks/useRefreshInquiry.ts
  src/pages/Inquiry/hooks/useSubmitInquiry.ts
  src/pages/Setting/Withdrawal/useWithdrawal.ts
Labels: enhancement

#157 [AUTH] 아이디, 비밀번호 찾기 이슈 수정
  src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
  src/pages/Auth/FindIdPassword/PC/index.tsx
  src/pages/Auth/FindIdPassword/mobile/ChangePassword.tsx
  src/pages/Auth/FindIdPassword/mobile/Input.tsx
  src/pages/Auth/FindIdPassword/mobile/Modal.tsx
  src/pages/Auth/FindIdPassword/mobile/VerifyCode.tsx
  src/pages/Auth/FindIdPassword/mobile/VerifyField.tsx
  src/pages/Auth/FindIdPassword/mobile/index.module.scss
  src/pages/Auth/FindIdPassword/mobile/index.tsx
Labels: Refactoring

#132 [POST] 단일 핀 조회 기능
  src/api/scrap/entity.ts
  src/api/scrap/index.ts
  src/api/shop/entity.ts
  src/api/shop/index.ts
  src/components/ImageCarousel/ImageCarousel.module.scss
  src/components/ImageCarousel/index.tsx
  src/components/common/SideNavigation/components/Pin.module.scss
  src/components/common/SideNavigation/components/index.tsx
  src/components/common/SideNavigation/hooks/usePin.ts
  src/components/common/SideNavigation/hooks/useScrapId.ts
  src/components/common/SideNavigation/index.tsx
  src/pages/Home/components/Map/components/MarkerHtml/index.tsx
  src/pages/Home/components/Map/components/MobileOptions/index.tsx
  src/pages/Home/components/Map/hooks/useMarker.ts
  src/pages/Home/components/Map/index.tsx
  src/pages/Home/components/Pin/index.tsx
  src/pages/ShopDetail/components/ImageCarousel/ImageCarousel.module.scss
  src/pages/ShopDetail/components/ImageCarousel/index.tsx
  src/pages/ShopDetail/index.tsx
  src/store/filter.ts
  src/store/placeId.ts
Labels: enhancement, Refactoring

#187 [Map] 맵 UI 수정 및 리팩토링
  src/components/DataTable/DataTable.module.scss
  src/components/DataTable/index.tsx
  src/components/editor/TextEditor/TextEditor.module.scss
  src/components/editor/TextEditor/index.tsx
  src/layout/DefaultLayout/index.tsx
  src/pages/Auth/FindIdPassword/hooks/entity.ts
  src/pages/Auth/FindIdPassword/hooks/useInputCheck.ts
  src/pages/Auth/FindIdPassword/mobile/VerifyCode.tsx
  src/pages/Auth/Login/hooks/entity.ts
  src/pages/Auth/Login/hooks/useLoginRequest.ts
  src/pages/Auth/Login/index.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/components/LocationInfo/LocationInfo.module.scss
  src/pages/Home/components/LocationInfo/index.tsx
  src/pages/Home/components/Map/Map.module.scss
  src/pages/Home/components/Map/components/Location/index.tsx
  src/pages/Home/components/Map/components/LocationSelectButton/LocationSelectButton.module.scss
  src/pages/Home/components/Map/components/LocationSelectButton/index.tsx
  src/pages/Home/components/Map/components/LocationSelectModal/LocationSelectModal.module.scss
  src/pages/Home/components/Map/components/LocationSelectModal/index.tsx
  src/pages/Home/components/Map/hooks/useHome.ts
  src/pages/Home/components/Map/index.tsx
  src/pages/Home/index.tsx
  src/pages/Inquiry/Inquiry/Inquiry.module.scss
  src/pages/Inquiry/Inquiry/components/InquirySelectButton/InquirySelectButton.module.scss
  src/pages/Notice/Notice.module.scss
  src/pages/Notice/index.tsx
  src/pages/Setting/Mobile/IdChange.tsx
  src/pages/Setting/Mobile/Setting.module.scss
  src/pages/Setting/Mobile/index.tsx
  src/pages/Setting/PC/ManageAccount.tsx
  src/pages/Setting/hooks/useModifyPassword.ts
  src/pages/Setting/hooks/usePasswordState.ts
Labels: Refactoring

#191 [Search] 검색 api 수정, UI 수정
  src/api/scrap/entity.ts
  src/api/shop/entity.ts
  src/api/shop/index.ts
  src/components/ImageCarousel/ImageCarousel.module.scss
  src/components/common/SideNavigation/components/index.tsx
  src/index.scss
  src/pages/Home/Home.module.scss
  src/pages/Search/SearchPost.tsx
  src/pages/Search/SearchShop.tsx
  src/pages/Search/components/RecentSearches/index.module.scss
  src/pages/Search/components/SearchBar/SearchBar.module.scss
  src/pages/SearchDetails/SearchDetails.module.scss
  src/pages/SearchDetails/components/SearchItem.tsx
  src/pages/ShopDetail/ShopDetail.module.scss
  src/pages/ShopDetail/components/Map/Map.module.scss
  src/pages/ShopDetail/components/Map/index.tsx
  src/pages/ShopDetail/components/ScrapButton/index.tsx
  src/pages/ShopDetail/components/SectionHeader/SectionHeader.module.scss
  src/pages/ShopDetail/components/SectionHeader/index.tsx
  src/pages/ShopDetail/index.tsx
  src/pages/ShopDetail/mock.ts
  src/utils/hooks/useScrapId.ts
Labels: enhancement, UI

#233 fix: 롤링 배너,이벤트 전파, 전체 삭제 이슈 해결
  src/pages/Search/components/RecentItem/RecentItem.module.scss
  src/pages/Search/components/RecentItem/index.tsx
  src/pages/Search/components/RecentSearches/index.tsx
  src/pages/Search/components/RollingBanner/RollingBanner.module.scss
  src/pages/Search/components/RollingBanner/index.tsx
  src/pages/Search/components/SearchInput/index.tsx
  src/pages/Search/components/SuggestionItem/index.tsx
  src/pages/Search/components/Suggestions/index.tsx
  src/pages/Search/hooks/useRecentSearches.ts
  src/pages/Search/index.tsx
  src/pages/Search/static/entity.ts
  src/pages/SearchDetails/components/SearchItem.tsx
  src/pages/SearchDetails/index.tsx
  src/store/text.ts
Labels: bug, Refactoring

#236 fix: 사이드바 요소 가려지는 문제
  src/assets/svg/search/mobile-delete.svg
  src/layout/DefaultLayout/DefaultLayout.module.scss
  src/layout/DefaultLayout/index.tsx
  src/pages/Follow/components/FollowProfile.module.scss
  src/pages/Follow/index.module.scss
  src/pages/Home/Home.module.scss
  src/pages/Inquiry/Inquire/Inquire.module.scss
  src/pages/Inquiry/Inquire/components/InquireForm/InquireForm.module.scss
  src/pages/Inquiry/Inquiry/Inquiry.module.scss
  src/pages/Search/Search.module.scss
  src/pages/Search/components/NotFoundPage/NotFoundPage.module.scss
  src/pages/Search/components/RecentItem/RecentItem.module.scss
  src/pages/Search/components/RecentItem/index.tsx
  src/pages/Search/components/SearchInput/SearchInput.module.scss
  src/pages/Search/components/Suggestions/Suggestions.module.scss
  src/pages/Setting/Mobile/IdChange.tsx
  src/pages/Setting/Mobile/Setting.module.scss
  src/pages/Setting/PC/PcSetting.module.scss
  src/pages/Setting/Withdrawal/Withdrawal.module.scss
Labels: bug, Refactoring

#247 fix: 비회원 북마크시 로그인으로 이동
  src/pages/ShopDetail/index.tsx
  src/utils/hooks/useScrap.ts
Labels: bug
